name: staging

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      ref:
        description: Commit SHA / branch to deploy
        default: master
        required: true

jobs:
  staging:
    uses: ./.github/workflows/shared.yml
    with:
      cluster_name: staging
      environment: staging
      subscription_id: a07f60a2-416e-42c7-87a5-5f046bf0ddee # Devolutions Staging
      ref: ${{ inputs.ref }}
    secrets: inherit
